spring.application.name=mutation-signature

## Default paths for resources
#mutation.signature.vcf.path=D:/Mohammad_Siam_Ahmed_Rana/Mutation_Signature/Resources/sample/Example_INDEL_VCF02.hg38.vcf
#mutation.signature.genome.path=D:/Mohammad_Siam_Ahmed_Rana/Mutation_Signature/Resources/genome/GRCh38.fa
#mutation.signature.output.path=Example_INDEL_VCF02.hg38.txt
#
## Logging
#logging.level.com.company.mutationsignature=DEBUG


# Absolute paths for your Windows environment
mutation.signature.vcf.path=D:/Mohammad_Siam_Ahmed_Rana/Mutation_Signature/Resources/sample/Example_INDEL_VCF02.hg38.vcf
mutation.signature.genome.path=D:/Mohammad_Siam_Ahmed_Rana/Mutation_Signature/Resources/genome/GRCh38.fa
mutation.signature.output.path=D:/Mohammad_Siam_Ahmed_Rana/Mutation_Signature/Resources/sample/Example_INDEL_VCF02.hg38.txt
mutation.signature.cosmic.path=D:/Mohammad_Siam_Ahmed_Rana/Mutation_Signature/Resources/cosmic/COSMIC_Human_ID-83_GRCh37_v3.6.tsv

logging.level.com.company.mutationsignature=DEBUG